theme: jekyll-theme-minimal
title: AI周报整理
description: 搜集AI相关前沿技术和最新应用

markdown:

<p style="text-align:center">AI周报(0111-0117)</p>

### 1、AI应用——京东健康发布医院全场景应用大模型， 面向患者、医生、医院

​	2025年1月11日，京东健康数智医疗大会在北京成功举行。会上，京东健康全新发布了医院全场景应用大模型产品——**京东卓医（JOY DOC）**，**产品面向患者就医、医生诊疗、医院管理全场景**。京东健康依托“京医千询”医疗大模型技术底座，通过构建京东卓医“个人就医管家”（AiP-Ai for Patient）、 “医生数字分身”（AiD-Ai for Doctor）、 “未来数字医院”（AiH-Ai forHospital），致力于让患者看病更舒心、医生临床科研更高效、医院整体运营更轻松。
